

POST http://localhost:3000/reports
Content-Type: application/json

{
    "make":"hyundai",
    "model":"sonata",
    "year":1940,
    "mileage":1,
    "lng":0,
    "lat":0,
    "price":500
}


### CHANGE APPROVAL
PATCH http://localhost:3000/reports/3
Content-Type: application/json

{
    "approved":true
}

### CHANGE APPROVAL
PATCH http://localhost:3000/reports/3
Content-Type: application/json

{
    "approved":false
}