
### Create a new User
POST http://localhost:3000/auth/signup
Content-Type: application/json
//와 이거 붙여놔야되네

{
    "email":"ㅇㄴㅁ@nasdc.com",
    "password":"strdassing"

}


### Find user Id

GET http://localhost:3000/auth/3


### Find all user  with a given email

GET http://localhost:3000/auth?email=ㅇㄴㅁ@nasdc.com


### Delete a user with a given id

DELETE http://localhost:3000/auth/2


### Update a user With a given id

PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email":"zzz1zz@zzz.com"
}